export type EffectClass =
  'Damage'
  | 'ChangeHp'
  | 'MultipleAttack'
  | 'ChangeView'
  | 'MultipleDefence'
  | 'ChangeAgi'
  | 'RemoveBuff'
  | 'SpdDeferenceDamage'
  | 'Heal'
  | 'ComboPlus'
  | 'ComboDamage'
  | 'Aggregation'
  | 'HealthDamage'
  | 'Provocation'
  | 'Cure'
  | 'MultipleBaseView'
  | 'NowViewDamage'
  | 'ChangeSkillProve'
  | 'NeedViewChange'
  | 'StatusNumDamage'
  | 'Silence'
  | 'MoreTurn'
  | 'Penetration'
  | 'IncreaseLAH'
  | 'MultipleHp'
  | 'IncreaseExp'
  | 'NeedViewValueChange'
;
